<a href="https://colab.research.google.com/github/pachterlab/BI-BE-CS-183-2023/blob/main/HW1/pythonReview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bi/Be/Cs 183 2022-2023: Intro to Computational Biology
TAs: Meichen Fang, Tara Chari, Zitong (Jerry) Wang


In [ ]:
#To run a code cell, select the cell and hit Command/Ctrl+Enter or click the run/play symbol
#Click Insert --> Code Cell or the '+ Code' option to insert a new code cell

In [ ]:
#Click Insert --> Text Cell or the '+ Text' option to insert a cell for text as below

Text here for descriptions, explanations, etc

## **Variables and Data Types**

Numerical Types

In [ ]:
#Integers
x = 10
y = -50

#Float
a = 10.0

#Complex
c = 3.14j



In [ ]:
#Print function (built-in)
print(x)
print(y)

print(a)

print(c)

10
-50
10.0
3.14j


In [ ]:
#Assign multiple variables at the same time
a = b = c = 5

i,j,k = 1,2,3


In [ ]:
b = 3


In [ ]:
a

5

Strings

In [ ]:
word = 'Hello World!'

# Prints complete string
print(word)
# Prints first character of the string
print(word[0])

# Prints third through fifth characters
print(word[2:5]) #2:5, 

Hello World!
H
llo


In [ ]:
#cannot do
word[0] = 'B'

TypeError: ignored

In [ ]:
#Indexing starts at 0
#0:5 is 0,1,2,3,4

Lists: Can change their size and their elements

In [ ]:
l = [ 'abcd', 786 , 2.23, 'john', 70.2 ]
small_l = [123, 'john']

# Prints complete list
print(l)
# Prints first element of the list
print(l[0])
# Prints elements starting from 2nd till 3rd 
print(l[1:3])
# Prints elements starting from 3rd element
print(l[2:])

['abcd', 786, 2.23, 'john', 70.2]
abcd
[786, 2.23]
[2.23, 'john', 70.2]


In [ ]:
l[-1]

70.2

In [ ]:
# Prints list two times
print(small_l * 2)
# Prints concatenated lists
print(small_l + small_l +small_l)

[123, 'john', 123, 'john']
[123, 'john', 123, 'john', 123, 'john']


In [ ]:
small_l == [123, 'john']


True

In [ ]:
123 in small_l

True

In [ ]:
#Don't call variables 'list' (or str)
#list = [1,2,3]

#d = list([1,2,3]) will give an error

Tuples: Essentially 'Read-only'

In [ ]:
tup = ( 'abcd', 786 , 2.23, 'john', 70.2  )
small_tup = (123, 'john')

# Prints the complete tuple
print(tup)
# Prints first element of the tuple
print(tup[0])
# Prints elements of the tuple starting from 2nd till 3rd 
print(tup[1:3])
# Prints elements of the tuple starting from 3rd element
print(tup[2:])
# Prints the contents of the tuple twice
print(small_tup *2)
# Prints concatenated tuples
print(tup + small_tup)

('abcd', 786, 2.23, 'john', 70.2)
abcd
(786, 2.23)
(2.23, 'john', 70.2)
(123, 'john', 123, 'john')
('abcd', 786, 2.23, 'john', 70.2, 123, 'john')


In [ ]:
#Cannot do
tup[2] = 5

TypeError: ignored

In [ ]:
l = [1,2,3]
l

In [ ]:
l[0] = 4
l

[4, 786, 2.23, 'john', 70.2]

Dictionaries

In [ ]:

grads = {}
grads

{}

In [ ]:
grads = {}

#Add elements

grads['Amy'] = "G4"
grads['James'] = "G2"
grads['Total'] = 2

# Prints complete dictionary
print(grads)
# Prints value for Amy key
print(grads['Amy'])

# Prints all the keys
print(grads.keys())
# Prints all the values
print(grads.values())

{'Amy': 'G4', 'James': 'G2', 'Total': 2}
G4
dict_keys(['Amy', 'James', 'Total'])
dict_values(['G4', 'G2', 2])


In [ ]:
print(grads['Amy'])

G4


Conversions

In [ ]:
#int(), str(), list() all functions

f = 32.9
#Not a rounding function
int(f)

32

In [ ]:
#Convert to string
i = 32
str(i)

'32'

In [ ]:
#Concatenate strings 
str(i) + str(i)

'3232'

In [ ]:
print('This is i: ',i)

This is i:  32


## **Loops and List Comprehension**

Operators

In [ ]:
#Examples of operators
x = 1 + 2
y = 1/2

z = 4%2

a = 1*2



In [ ]:
print(x)
print(y)
print(z)
print(a)

3
0.5
0
2


In [ ]:
print(a == z) #not the same as a = z

print(a != z)

print(a > z)

print(a <= z)

False
True
True
False


In [ ]:
~(a == z)

-1

In [ ]:
#AND , OR operators
#&, |, ^

print((a > z) & (a != z)) #True & True


True


Looping (Indentation very important here!)

In [ ]:
#Set condition
if (a > 0):
  #Action if condition True
  print('Nonzero!')

Nonzero!


In [ ]:
#Make a test list
test_list = [1,2,3,4,5]
len(test_list)

5

In [ ]:
#Loop through each value in list and print out operation on those values
for i in range(len(test_list)):
#Range will give you values from 0:5 (0,1,2,3,4)
  i += 1
  
  #Equivalent to i = i + 1

  print(i)


1
2
3
4
5


In [ ]:
#Example while loop
z = 5
while(z > 0):
  z -= 1
  print(z)

4
3
2
1
0


In [ ]:
#Use += with lists

#Add things to empty list
example = []

example += [2]

example

[2]

In [ ]:
example += [3]

In [ ]:
example

[2, 3]

List Comprehension (looping through lists and operating on items)

In [ ]:
#Loops within list
fruits = ["apple", "banana","cherry","kiwi","mango"]

newlist = [x for x in fruits if "a" in x]

newlist

['apple', 'banana', 'mango']

In [ ]:
for i in fruits:
  print(i)

apple
banana
cherry
kiwi
mango


## **Functions**

Define functions when you have a task you want to run multiple times, possibly on different inputs

In [ ]:
#Define a function
def say_hello():
  print('Hello World!')

In [ ]:
say_hello()
say_hello()

Hello World!
Hello World!


In [ ]:
#Define a function that returns a value
def mean(values):
  avg = sum(values)/len(values)
  return avg

In [ ]:
#Call function with input
mean([1,2,3])

2.0

## **Useful Packages and Data Types**

Numpy (faster calculations with arrays/matrices)

In [ ]:
import numpy as np #np is abbreviation

#Call functions within numpy package
np.mean([1,2,3])

2.0

In [ ]:
#Test on numpy array
arr = np.array([1,2,3,4])
arr.mean()

2.5

In [ ]:
#Access values

arr[3] = 6
arr
#Every other value

array([1, 2, 3, 6])

In [ ]:
#Create `empty' array
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr[0,1] = 1
arr

array([[0., 1., 0.],
       [0., 0., 0.]])

Pandas

In [ ]:
import pandas as pd

In [ ]:
#Large lookup table/dictionary --> pandas DataFrame
df = pd.DataFrame()

In [ ]:
#Populate dataframe
df['Names'] = ['Amy','James','Kelly']
df['Ages'] = [22,24,26]
df

Names  Ages
0    Amy    22
1  James    24
2  Kelly    26

In [ ]:
#See df['Names'] column
df.Names

0      Amy
1    James
2    Kelly
Name: Names, dtype: object

In [ ]:
#Check for conditions
df['Names'].isin(['Amy','Kelly'])

0     True
1    False
2     True
Name: Names, dtype: bool

In [ ]:
#Subset your dataframe with conditions
df[df['Names'].isin(['Amy','Kelly'])]

Names  Ages
0    Amy    22
2  Kelly    26